language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build insights-rbac-api-client.gemspec
  - gem install ./insights-rbac-api-client-1.0.1.gem
